// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqiZbMWPDJQFN64rw6ObyzcbSxPZCQiU',
    appId: '1:681763569863:web:103cc3465275f0e598bee2',
    messagingSenderId: '681763569863',
    projectId: 'plantcare-a2e7e',
    authDomain: 'plantcare-a2e7e.firebaseapp.com',
    storageBucket: 'plantcare-a2e7e.firebasestorage.app',
    measurementId: 'G-BKTC7PLR8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmMN7f1QC66Bwz5dqIT_QFfc0xdIxXkvY',
    appId: '1:681763569863:android:2a42a2e11c43807898bee2',
    messagingSenderId: '681763569863',
    projectId: 'plantcare-a2e7e',
    storageBucket: 'plantcare-a2e7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWo47mULgUVdC0K4pK5uaHU76P7_iTd8k',
    appId: '1:681763569863:ios:25120a028fed6c1398bee2',
    messagingSenderId: '681763569863',
    projectId: 'plantcare-a2e7e',
    storageBucket: 'plantcare-a2e7e.firebasestorage.app',
    iosBundleId: 'com.example.plantcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWo47mULgUVdC0K4pK5uaHU76P7_iTd8k',
    appId: '1:681763569863:ios:25120a028fed6c1398bee2',
    messagingSenderId: '681763569863',
    projectId: 'plantcare-a2e7e',
    storageBucket: 'plantcare-a2e7e.firebasestorage.app',
    iosBundleId: 'com.example.plantcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHqiZbMWPDJQFN64rw6ObyzcbSxPZCQiU',
    appId: '1:681763569863:web:2e4b63f2ea83651b98bee2',
    messagingSenderId: '681763569863',
    projectId: 'plantcare-a2e7e',
    authDomain: 'plantcare-a2e7e.firebaseapp.com',
    storageBucket: 'plantcare-a2e7e.firebasestorage.app',
    measurementId: 'G-KND5FQ9JJ2',
  );
}
